const ViewDocuments = async (invoice) => {
    let Report = `
    select * from 
(select 
SALESINVOICEHEADER.INVOICENUMBER, 
SALESINVOICEHEADER.INVOICEDATE, 
SALESINVOICEHEADER.INVOICETAXAMOUNT, 
SALESINVOICEHEADER.INVOICETOTALAMOUNT, 
SALESINVOICEHEADER.INVOICEFREIGHTAMOUNT, 
SALESINVOICEHEADER.INVOICENETTAMOUNT, 
SALESINVOICEHEADER.INVOICEORCREDIT, 
SALESINVOICEGROUPING.ORDERNUMBER, 
SALESINVOICELINES.INVOICEUNITPRICE, 
SALESINVOICELINES.EXTENDEDNETTPRICE, 
SALESINVOICELINES.INVOICEUNITTAX, 
SALESINVOICELINES.INVOICEQTY, 
SALESINVOICELINES.LINECODE, 
SALESINVOICELINES.LINEDESCRIPTION, 
SALESHEADER.INVOICENOTES, 
SALESHEADER.ORDERPHONE, 
SALESHEADER.ORDERFAX, 
SALESHEADER.ORDERADDRESS1, 
SALESHEADER.ORDERADDRESS2, 
SALESHEADER.ORDERADDRESS3, 
SALESHEADER.ORDERCITY, 
SALESHEADER.ORDERSTATE, 
SALESHEADER.ORDERPOSTALCODE, 
SALESHEADER.REQUIREDDATE, 
SALESHEADER.PURCHASEREFERENCE, 
SALESHEADER.SHIPPINGMETHOD, 
SALESHEADER.ADDITIONALFIELD_7, 
SALESHEADER.ORDERNOTES, 
CUSTOMERMASTER.CUSTOMER, 
CUSTOMERMASTER.CUSTOMERCOMMENT, 
CUSTOMERMASTER.CUSTOMERNOTES, 
CUSTOMERMASTER.CUSTOMERPHONE, 
CUSTOMERMASTER.CUSTOMERFAX, 
CUSTOMERMASTER.CREDITTERM, 
CUSTOMERMASTER.CUSTOMERTYPE,  
CUSTOMERMASTER.TOTALAMOUNTUNAPPLIED, 
ITEMMASTER.ITEMCATEGORY as "CAT" 
from 
SALESHEADER, 
SALESINVOICEHEADER, 
SALESINVOICEGROUPING, 
SALESINVOICELINES, 
CUSTOMERMASTER, 
ITEMMASTER 
where 
SALESINVOICEHEADER.INVOICENUMBER = SALESINVOICEGROUPING.INVOICENUMBER 
and SALESINVOICEHEADER.INVOICENUMBER = SALESINVOICELINES.INVOICENUMBER and 
SALESINVOICELINES.LINECODE = ITEMMASTER.ITEMCODE and 
SALESINVOICEGROUPING.ORDERNUMBER = SALESHEADER.ORDERNUMBER and 
SALESINVOICEHEADER.CUSTOMER = CUSTOMERMASTER.CUSTOMER and 
SALESINVOICEHEADER.INVOICENUMBER = '${invoice}'  
union all
select 
SALESINVOICEHEADER.INVOICENUMBER, 
SALESINVOICEHEADER.INVOICEDATE, 
SALESINVOICEHEADER.INVOICETAXAMOUNT, 
SALESINVOICEHEADER.INVOICETOTALAMOUNT, 
SALESINVOICEHEADER.INVOICEFREIGHTAMOUNT, 
SALESINVOICEHEADER.INVOICENETTAMOUNT, 
SALESINVOICEHEADER.INVOICEORCREDIT, 
SALESINVOICEGROUPING.ORDERNUMBER, 
SALESINVOICELINES.INVOICEUNITPRICE, 
SALESINVOICELINES.EXTENDEDNETTPRICE, 
SALESINVOICELINES.INVOICEUNITTAX, 
SALESINVOICELINES.INVOICEQTY, 
SALESINVOICELINES.LINECODE, 
SALESINVOICELINES.LINEDESCRIPTION, 
SALESHEADER.INVOICENOTES, 
SALESHEADER.ORDERPHONE, 
SALESHEADER.ORDERFAX, 
SALESHEADER.ORDERADDRESS1, 
SALESHEADER.ORDERADDRESS2, 
SALESHEADER.ORDERADDRESS3, 
SALESHEADER.ORDERCITY, 
SALESHEADER.ORDERSTATE, 
SALESHEADER.ORDERPOSTALCODE, 
SALESHEADER.REQUIREDDATE, 
SALESHEADER.PURCHASEREFERENCE, 
SALESHEADER.SHIPPINGMETHOD, 
SALESHEADER.ADDITIONALFIELD_7, 
SALESHEADER.ORDERNOTES, 
CUSTOMERMASTER.CUSTOMER, 
CUSTOMERMASTER.CUSTOMERCOMMENT, 
CUSTOMERMASTER.CUSTOMERNOTES, 
CUSTOMERMASTER.CUSTOMERPHONE, 
CUSTOMERMASTER.CUSTOMERFAX, 
CUSTOMERMASTER.CREDITTERM, 
CUSTOMERMASTER.CUSTOMERTYPE,  
CUSTOMERMASTER.TOTALAMOUNTUNAPPLIED, 
DESCRIPTORMASTER.DESCRIPTORCATEGORY as "CAT" 
from 
SALESHEADER, 
SALESINVOICEHEADER, 
SALESINVOICEGROUPING, 
SALESINVOICELINES, 
CUSTOMERMASTER, 
DESCRIPTORMASTER 
where 
SALESINVOICEHEADER.INVOICENUMBER = SALESINVOICEGROUPING.INVOICENUMBER 
and SALESINVOICEHEADER.INVOICENUMBER = SALESINVOICELINES.INVOICENUMBER and 
SALESINVOICELINES.LINECODE = DESCRIPTORMASTER.DESCRIPTORCODE and 
SALESINVOICEGROUPING.ORDERNUMBER = SALESHEADER.ORDERNUMBER and 
SALESINVOICEHEADER.CUSTOMER = CUSTOMERMASTER.CUSTOMER and 
SALESINVOICEHEADER.INVOICENUMBER = '${invoice}') INV 
order by 
INV.INVOICEDATE, INV.SHIPPINGMETHOD, INV.ADDITIONALFIELD_7, INV.INVOICENUMBER, INV.CAT asc, UPPER(INV.LINEDESCRIPTION) asc
    `;
    const requestEndpoint = `http://sw.unifresh.com.au:82/sqlquery/?apikey=Ytm1VIhM2ai7fewNDR1QpEypr%2FuqXBZvspibPCxoBoLiXyEA8DVaP2BcAiw6th%2Bvgj7Gcr%2FwuXPDWyCpABxO3FQLtzLlgOsh4YFHHNcCx55E4LUDYWA%3D&format=json`;
    const response = await fetch(requestEndpoint, {
      method: "POST",
      body: Report,
      headers: {
        "Content-Type": "application/json",
      },
    });
    const jsonResponse = await response.json();
    return jsonResponse;
  };
  module.exports = ViewDocuments;
  