const Report = `

select first 1
SALESINVOICEHEADER.INVOICENUMBER, 
SALESINVOICEHEADER.INVOICEDATE, 
SALESINVOICEHEADER.INVOICETAXAMOUNT, 
SALESINVOICEHEADER.INVOICETOTALAMOUNT, 
SALESINVOICEHEADER.INVOICEFREIGHTAMOUNT, 
SALESINVOICEHEADER.INVOICENETTAMOUNT, 
SALESINVOICEGROUPING.INVOICENUMBER, 
SALESINVOICEGROUPING.ORDERNUMBER, 
SALESINVOICELINES.INVOICEUNITPRICE, 
SALESINVOICELINES.EXTENDEDNETTPRICE, 
SALESINVOICELINES.INVOICEUNITTAX, 
SALESINVOICELINES.INVOICEQTY, 
SALESINVOICELINES.LINECODE, 
SALESINVOICELINES.LINEDESCRIPTION, 
SALESHEADER.ORDERNUMBER, 
SALESHEADER.INVOICENOTES, 
SALESHEADER.ORDERPHONE, 
SALESHEADER.ORDERFAX, 
SALESHEADER.ORDERADDRESS1, 
SALESHEADER.ORDERADDRESS2, 
SALESHEADER.ORDERADDRESS3, 
SALESHEADER.ORDERCITY, 
SALESHEADER.ORDERSTATE, 
SALESHEADER.ORDERPOSTALCODE, 
SALESHEADER.ORDERPOSTALCODE, 
SALESHEADER.REQUIREDDATE, 
SALESHEADER.PURCHASEREFERENCE, 
SALESHEADER.SHIPPINGMETHOD, 
SALESHEADER.ADDITIONALFIELD_7, 
SALESHEADER.ORDERNOTES, 
CUSTOMERMASTER.CUSTOMER, 
CUSTOMERMASTER.CUSTOMERCOMMENT, 
CUSTOMERMASTER.CUSTOMERNOTES, 
CUSTOMERMASTER.MOBILITYNOTES, 
CUSTOMERMASTER.CUSTOMERPHONE, 
CUSTOMERMASTER.CUSTOMERFAX, 
CUSTOMERMASTER.CREDITTERM, 
CUSTOMERMASTER.CUSTOMERTYPE,  
CUSTOMERMASTER.TOTALAMOUNTUNAPPLIED, 
CUSTOMERMASTER.CODE1, 
CUSTOMERMASTER.CODE2, 
CUSTOMERMASTER.CODE3, 
CUSTOMERMASTER.CODE4, 
CUSTOMERMASTER.ADDITIONALFIELD_1 as "CUSTOMERGROUP", 
CUSTOMERMASTER.ADDITIONALFIELD_38, 
CUSTOMERMASTER.ADDITIONALFIELD_30, 
CUSTOMERMASTER.ADDITIONALFIELD_31, 
CUSTOMERMASTER.ADDITIONALFIELD_36, 
CUSTOMERMASTER.ADDITIONALFIELD_53 as "PRINTPRICES", 
ITEMMASTER.ITEMCATEGORY, 
CAST(ITEMMASTER.ADDITIONALFIELD_1 as DECIMAL(11,5)) * SALESINVOICELINES.INVOICEQTY as "KILOGRAMS" 
from 
SALESHEADER, 
SALESINVOICEHEADER, 
SALESINVOICEGROUPING, 
SALESINVOICELINES, 
CUSTOMERMASTER, 
ITEMMASTER 
where 
SALESINVOICEHEADER.INVOICENUMBER = SALESINVOICEGROUPING.INVOICENUMBER 

`;

const Get_Request = async (e) => {
  const requestEndpoint = `http://sw.unifresh.com.au:82/sqlquery/?apikey=Ytm1VIhM2ai7fewNDR1QpEypr%2FuqXBZvspibPCxoBoLiXyEA8DVaP2BcAiw6th%2Bvgj7Gcr%2FwuXPDWyCpABxO3FQLtzLlgOsh4YFHHNcCx55E4LUDYWA%3D&format=json`;
  const response = await fetch(requestEndpoint, {
    method: "POST",
    body: Report,
    headers: {
      "Content-Type": "application/json",
    },
  });
  const jsonResponse = await response.json();
  return jsonResponse;
};
module.exports = Get_Request;
  